# Generated by Django 2.0.2 on 2019-02-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='newsTitle',
            new_name='title',
        ),
    ]
