# Generated by Django 2.0.2 on 2019-01-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topText', models.TextField()),
                ('bottomBlockText', models.CharField(max_length=250)),
                ('bottomImage1', models.ImageField(upload_to='images/')),
                ('bottomImage1Text', models.CharField(max_length=250)),
                ('bottomImage2', models.ImageField(upload_to='images/')),
                ('bottomImage2Text', models.CharField(max_length=250)),
                ('bottomImage3', models.ImageField(upload_to='images/')),
                ('bottomImage3Text', models.CharField(max_length=250)),
                ('bottomImage4', models.ImageField(upload_to='images/')),
                ('bottomImage4Text', models.CharField(max_length=250)),
            ],
        ),
    ]
