# Generated by Django 2.0.2 on 2019-02-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpage',
            name='title',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AddField(
            model_name='frontpage',
            name='topTextTitle',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AddField(
            model_name='frontpage',
            name='topphone1',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AddField(
            model_name='frontpage',
            name='topphone2',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AlterField(
            model_name='frontpage',
            name='bottomBlockText',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AlterField(
            model_name='frontpage',
            name='bottomImage1',
            field=models.ImageField(default='null', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='frontpage',
            name='bottomImage1Text',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AlterField(
            model_name='frontpage',
            name='bottomImage2Text',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AlterField(
            model_name='frontpage',
            name='bottomImage3Text',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AlterField(
            model_name='frontpage',
            name='bottomImage4Text',
            field=models.CharField(default='null', max_length=250),
        ),
    ]
