# Generated by Django 2.0.2 on 2019-02-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='catalogTitle',
        ),
        migrations.AddField(
            model_name='catalog',
            name='title',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='catalogCost',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='catalogGramms',
            field=models.CharField(default='null', max_length=250),
        ),
    ]
