# Generated by Django 2.0.2 on 2019-02-09 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='recipesTitle',
            new_name='title',
        ),
    ]
